name: Production CD
on:
  push:
    branches: ["main"]
jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      dsa: ${{ steps.filter.outputs.dsa }}
      qr: ${{ steps.filter.outputs.qr }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dsa:
              - 'dsa/**'
            qr:
              - 'qr-code/**'
  build-qr:
    needs: changes
    if: ${{ needs.changes.outputs.qr == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        run: |
          cd qr
          make build
          make docker-push TAG=$(git rev-parse --short "$GITHUB_SHA")
          make docker-push TAG=latest

  build-dsa:
    needs: changes
    if: ${{ needs.changes.outputs.dsa == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        run: |
          cd dsa
          make build
          make docker-push TAG=$(git rev-parse --short "$GITHUB_SHA")
          make docker-push TAG=latest

  deploy-qr:
    needs: build-qr
    name: Rollout QR Code Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Rollout deployment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            kubectl rollout restart deployment qrcode-frontend -n qrcode

  deploy-dsa:
    needs: build-dsa
    name: Rollout DSA Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Rollout deployment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            kubectl rollout restart deployment dsa-frontend -n dsa
